Save-Server: true # If the server should be saved - Must be a boolean value
Save-Interval: 90 # Interval between saves in seconds - Must be a boolean value
Announce-Saves: true # If saves should be announced - Must be a boolean value
Announce-URL: images.unturnedserver.net/images/image.png # Announcement URL for the image when announcements are sent - Must be a string value without double quotes
